"""empty message

Revision ID: 0e8782bb3179
Revises: 92c5f95a73b9
Create Date: 2024-07-25 07:58:28.618521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8782bb3179'
down_revision = '92c5f95a73b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_type', sa.String(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('_user_item_uc', ['user_id', 'item_id', 'item_type'])
        batch_op.drop_constraint('favorites_starship_id__fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_people_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('starship_id_')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('starship_id_', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.create_foreign_key('favorites_starship_id__fkey', 'starships', ['starship_id_'], ['id'])
        batch_op.drop_constraint('_user_item_uc', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('item_type')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
