"""empty message

Revision ID: 92c5f95a73b9
Revises: 61d5b8194dec
Create Date: 2024-07-22 18:16:31.692889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c5f95a73b9'
down_revision = '61d5b8194dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorites_id_key', type_='unique')
        batch_op.drop_constraint('user_favorites_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorites_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_favorites_id_fkey', 'favorites', ['favorites_id'], ['id'])
        batch_op.create_unique_constraint('user_favorites_id_key', ['favorites_id'])

    # ### end Alembic commands ###
